<div class="basic_tb">  
<ul> 
	<li>
		{$lang.return_sale_order_no}： 
		{$rs.return_sale_order_no}
	</li>	
	<li>
		{$lang.deal_no}：
		{$rs.sale_order_no}
	</li>
	<li>
		{$lang.return_sale_date}：
		{$rs.fmd_return_order_date}
	</li>
	<li>
		{$lang.sum_quantity}： 
		{$rs.dml_quantity}
	</li>
	<li>
		{$lang.bulk_with_unit}：
		{$rs.dml_cube}
	</li>
	<li>
		{$lang.weight_with_unit}： 
		{$rs.dml_weight}
	</li>
	<li>
		{$lang.return_warehouse}：
		{$rs.w_name}
	</li>
	<li>
		{$lang.state}： 
		{$rs.dd_return_sale_order_state}
	</li>	
</ul>
</div>