<?php
return array(
	'CAINIAO_MODULE_DETAILS_KEY'			=> array(
												'ReturnSaleOrder'	=> 'logisticsDetail',
											),

	'CAINIAO_ADD_RETURN_ORDER_FIELDS'		=> array(//
												'logisticsOrderCode',
												'tradeId',
												'bizMode',
												'occurTime',
												'timeZone',
												'undeliveryOption',
												'photoType',
												'totalDeclaredPrice',
												'items' => array(
													'item'	=> array (
																'id',
																'declaredName',
																'categoryTreeEN',
																'nameEN',
																'nameCN',
																'categoryNameEN',
																'categoryNameCN',
																'quantity',
																'unitPrice',
																'weight',
																'hasBattery',
																'url',
															  ),
															),
												'buyerContact'	=> array (
																	'code',
																	'name',
																	'identityNo',
																	'phone',
																	'mobile',
																	'email',
																	'countryCode',
																	'country',
																	'province',
																	'city',
																	'district',
																	'streetAddress',
																	'zipCode',
																	'wangwangId',
																),
												'sellerContact'	=> array (
																	'code',
																	'name',
																	'identityNo',
																	'phone',
																	'mobile',
																	'email',
																	'countryCode',
																	'country',
																	'province',
																	'city',
																	'district',
																	'streetAddress',
																	'zipCode',
																	'wangwangId',
																),
											),
	'CAINIAO_ADD_RETURN_ORDER_TRACK_NO_FIELDS'	=> array(//
												'logisticsOrderCode',
												'mailNo',
												'tradeId',
												'bizMode',
												'occurTime',
												'timeZone',
												'totalDeclaredPrice',
												'items' => array(
													'item'	=> array (
																'id',
																'declaredName',
																'categoryTreeEN',
																'nameEN',
																'nameCN',
																'categoryNameEN',
																'categoryNameCN',
																'quantity',
																'unitPrice',
																'weight',
																'hasBattery',
																'url',
															  ),
															),
											),
	'CAINIAO_CONFIRM_RETURN_ORDER_FIELDS'	=> array(//
												'logisticsOrderCode',
												'bizMode',
												'occurTime',
												'timeZone',
												'undeliveryOption',
												'photoType',
											),
	'CAINIAO_RETURN_SALE_ORDER_INT_FIELDS'	=> array(//整数字段
												'undeliveryOption',
												'photoType',
												'items'		=> array(
																	'item'	=> array(
																					'quantity',
//																					'unitPrice',
//																					'weight',
																				),
																),
											),
	'CAINIAO_RETURN_SALE_ORDER_OPTIONAL_FIELDS'	=> array(//非必填字段
												'tradeId'				=> 'order_no',
												'timeZone'				=> 'timeZone',
												'photoType'				=> 'photoType',
												'totalDeclaredPrice'	=> 'totalDeclaredPrice',
												'items'					=> array(
																			'item'	=> array(
																						'declaredName'		=> 'declaredName',
																						'categoryTreeEN'	=> 'categoryTreeEN',
																						'nameCN'			=> 'nameCN',
																						'categoryNameEN'	=> 'categoryNameEN',
																						'weight'			=> 'weight',
																						'hasBattery'		=> 'hasBattery',
																						'url'				=> 'url',
																					),
																		),
												'buyerContact'			=> array(
																			'code'			=> 'code',
																			'identityNo'	=> 'identityNo',
																			'phone'			=> 'phone',
																			'mobile'		=> 'mobile',
																			'email'			=> 'email',
																			'country'		=> 'country_name',
																			'province'		=> 'company_name',
																			'district'		=> 'address2',
																			'zipCode'		=> 'post_code',
																			'wangwangId'	=> 'wangwangId',
																		),
												'sellerContact'			=> array(
																			'code'			=> 'code',
																			'identityNo'	=> 'identityNo',
																			'phone'			=> 'phone',
																			'mobile'		=> 'mobile',
																			'email'			=> 'email',
																			'country'		=> 'country_name',
																			'province'		=> 'company_name',
																			'district'		=> 'address2',
																			'zipCode'		=> 'post_code',
																			'wangwangId'	=> 'wangwangId',
																		),
											),
	'CAINIAO_RETURN_SALE_ORDER_SUB_KEY'			=> array(//一维子明细下标
												'buyerContact',
												'sellerContact',
											),
	'CAINIAO_RETURN_SALE_ORDER_SUB_KEYS'		=> array(//二维子明细下标
												'items',
											),
	'CAINIAO_RETURN_SALE_ORDER_THIRD_SUB_KEYS'		=> array(//三维子明细下标
												'items' => 'item',
											),
	'CAINIAO_RETURN_SALE_ORDER_DETAIL_KEYS'		=> array(
												'detail'	=> L('module_Product')
											),
	'CAINIAO_PRODUCT_DETAIL_FIELDS'		=> array(//明细对应属性ID的C变量下标
												C('MATERIAL_DESCRIPTION')	=> 'material',
												C('HS_CODE')				=> 'hsCode',
												C('DECLARED_VALUE')			=> 'declaredValue',
												C('SALE_PRICE')				=> 'unitPrice',
											),
	'CAINIAO_ADD_PRODUCT_FIELDS'		=> array(//新增产品
												'cust_sign',
												'categoryCode',
												'skuCode',
												'itemName',
												'specification',
												'declaredValue',
												'units',
												'weight',
												'length',
												'width',
												'height',
												'declaredName',
												'referenceCode',
												'description',
											),
	'CAINIAO_PRODUCT_OPTIONAL_FIELDS'	=> array(//非必填字段
												'specification'		=> 'specification',
												'description'		=> 'comments',
											),
	'CAINIAO_PRODUCT_EXTEND_FIELDS'		=> array(//扩展字段
												'categoryCode'		=> 'categoryCode',
												'specification'		=> 'specification',
												'units'				=> 'units',
												'declaredName'		=> 'declaredName',
												'url'				=> 'url',
											),
	'CAINIAO_ADD_SHIPPING_FIELDS'		=> array(//新增发货
												'cust_sign',//卖家auth_token
												'receiveOderCode',//物流编号
												'shipDate',//发货日期
												'deliveryDate',//交货日期
												'warehouseCode',//仓库编号
												'carrierCode',
												'insureType',
												'dutypayType',
												'referenceCode',
												'description',
												'customsType',
												'boxType',
												'lstItem'	=> array (
															'skuCode',
															'quantity',
															'acceptedQuantity',
															'packageType',
															'boxNumber',
															'goodsType',
															'weight',
														  ),
											),
	'CAINIAO_INSTOCK_INT_FIELDS'		=> array(//整数字段
												'carrierCode',
												'boxType',
												'lstItem'	=> array(
																'quantity',
															),
											),
	'CAINIAO_INSTOCK_OPTIONAL_FIELDS'	=> array(//非必填字段
												'description'			=> 'comments',
											),
	'CAINIAO_PRODUCT_EXTEND_FIELDS'		=> array(//扩展字段
												'insureType'		=> 'insureType',
												'dutypayType'		=> 'dutypayType',
												'referenceCode'		=> 'referenceCode',
												'customsType'		=> 'customsType',
												'lstItem'			=> array(
																		'packageType',
																		'goodsType',
																		'weight',
																	),
											),
	'CAINIAO_INSTOCK_SUB_KEYS'			=> array(//二维子明细下标
												'lstItem',
											),
	'CAINIAO_INSTOCK_THIRD_SUB_KEYS'	=> array(//三维子明细下标
												'lstItem' => '',
											),
	'CAINIAO_INSTOCK_DETAIL_KEYS'		=> array(
												'product'	=> L('module_Product')
											),
);