{ytt_table
	show=[
		['title'=>$lang.basic_name,'value'=>'company_name'],
		['title'=>$lang.address,'value'=>'address'],
		['title'=>'IVA','value'=>'iva'],
		['title'=>$lang.comments,'value'=>'comments']
	]
	from=$list.list
}